### ISSUE TITLE
Raleway 600 woff file 0 bytes

### ISSUE THREAD

**Issue by hbarnwheeler** [alfredxing/brick#56]
Raleway 600 does not exist (woff file of 0 bytes).  All other weights appear to be there.

**Comment by alfredxing** [comment]
Thanks for the bug report! I'll fix it as soon as I can.

**Comment by alfredxing** [comment]
Fixed in referenced commit. Thanks again for the report!

**Comment by hbarnwheeler** [comment]
I'm still getting a 0 byte woff file.  Perhaps this is a fastly caching issue?

**Comment by alfredxing** [comment]
Hmm, shouldn't be. I'm getting the right one now. I've cleared the Fastly cache for the file just in case, but try clearing your browser cache as well.

**Comment by hbarnwheeler** [comment]
It's working now.  I tried clearing browser cache before and that didn't help.  Thanks.
